<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Language;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    
                    $languages = [
                        ["name" => "Afar", "native_name" => "Afar"],
                        ["name" => "Afrikaans", "native_name" => "Afrikaans"],
                        ["name" => "Akan", "native_name" => "Akan"],
                        ["name" => "Albanian", "native_name" => "Shqip"],
                        ["name" => "Amharic", "native_name" => "Amharic"],
                        ["name" => "Arabic", "native_name" => "العربية"],
                        ["name" => "Aragonese", "native_name" => "Aragonese"],
                        ["name" => "Armenian", "native_name" => "Հայերեն"],
                        ["name" => "Assamese", "native_name" => "Assamese"],
                        ["name" => "Avaric", "native_name" => "Avaric"],
                        ["name" => "Avestan", "native_name" => "Avesta"],
                        ["name" => "Aymara", "native_name" => "aymar aru"],
                        ["name" => "Azerbaijani", "native_name" => "azebaycan dili"],
                        ["name" => "Bambara", "native_name" => "bamanankan"],
                        ["name" => "Bashkir", "native_name" => "Bashkir"],
                        ["name" => "Basque", "native_name" => "euskara"],
                        ["name" => "Belarusian", "native_name" => "Belarusian"],
                        ["name" => "Bengali", "native_name" => "বাংলা"],
                        ["name" => "Bihari", "native_name" => "Bihari"],
                        ["name" => "Bislama", "native_name" => "Bislama"],
                        ["name" => "Bosnian", "native_name" => " bosanski jezik"],
                        ["name" => "Breton", "native_name" => "brezhoneg"],
                        ["name" => "Bulgarian", "native_name" => "Bulgarian"],
                        ["name" => "Burmese", "native_name" => "Burmese"],
                        ["name" => "Catalan", "native_name" => "Català"],
                        ["name" => "Chamorro", "native_name" => "chamoru"],
                        ["name" => "Chechen", "native_name" => "Chechen"],
                        ["name" => "Chichewa", "native_name" => "chiChewa"],
                        ["name" => "Chinese", "native_name" => "中文"],
                        ["name" => "Chuvash", "native_name" => "Chuvash"],
                        ["name" => "Cornish", "native_name" => "Kernewek"],
                        ["name" => "Corsican", "native_name" => "corsu"],
                        ["name" => "Cree", "native_name" => "Cree"],
                        ["name" => "Croatian", "native_name" => "hrvatski"],
                        ["name" => "Czech", "native_name" => "cestina"],
                        ["name" => "Danish", "native_name" => "dansk"],
                        ["name" => "Dutch", "native_name" => "Nederlands"],
                        ["name" => "English", "native_name" => "English"],
                        ["name" => "Esperanto", "native_name" => "Esperanto"],
                        ["name" => "Estonian", "native_name" => "corsu"],
                        ["name" => "Ewe", "native_name" => "Euegbe"],
                        ["name" => "Faroese", "native_name" => "foroyskt"],
                        ["name" => "Fijian", "native_name" => "vosa Vakaviti"],
                        ["name" => "French", "native_name" => "Français"],
                        ["name" => "Fulah", "native_name" => "Fulfulde"],
                        ["name" => "Galician", "native_name" => "Galician"],
                        ["name" => "Georgian", "native_name" => "Georgian"],
                        ["name" => "German", "native_name" => "Deutsch"],
                        ["name" => "Greek", "native_name" => "Greek"],
                        ["name" => "Guarani", "native_name" => "Avanee"],
                        ["name" => "Gujarati", "native_name" => "Gujarati"],
                        ["name" => "Haitian", "native_name" => "Kreyol ayisyen"],
                        ["name" => "Hausa", "native_name" => "Hausa"],
                        ["name" => "Hebrew", "native_name" => "Hebrew"],
                        ["name" => "Herero", "native_name" => "Otjiherero"],
                        ["name" => "Hindi", "native_name" => "हिन्दी"],
                        ["name" => "Hiri  Motu", "native_name" => "Hiri Motu"],
                        ["name" => "Hungarian", "native_name" => "Magyar"],
                        ["name" => "Interlingua", "native_name" => "Interlingua"],
                        ["name" => "Indonesian", "native_name" => " Bahasa Indonesia"],
                        ["name" => "Irish", "native_name" => "Gaeilge"],
                        ["name" => "Igbo", "native_name" => "Asusu Igbo"],
                        ["name" => "Inupliaq", "native_name" => "Inupiatun"],
                        ["name" => "Ido", "native_name" => "Ido"],
                        ["name" => "Iceland", "native_name" => "Iselenska"],
                        ["name" => "Italian", "native_name" => "Italiano"],
                        ["name" => "Inuktitut", "native_name" => "Inuktitut"],
                        ["name" => "Japanese", "native_name" => "日本語"],
                        ["name" => "Javanese", "native_name" => "basa Jawa"],
                        ["name" => "Kalaallisut", "native_name" => "Kalaallisut"],
                        ["name" => "Kannada", "native_name" => "Kannada"],
                        ["name" => "Kanuri", "native_name" => "Kanuri"],
                        ["name" => "Kashmiri", "native_name" => "Kashmiri"],
                        ["name" => "Kazakh", "native_name" => "Kazakh"],
                        ["name" => "Khmer", "native_name" => "Khmer"],
                        ["name" => "Kikuyu", "native_name" => "Kikuyu"],
                        ["name" => "Kinyarwanda", "native_name" => "Ikinyarwanda"],
                        ["name" => "Kyrgyz", "native_name" => "Kyrgyz"],
                        ["name" => "Komi", "native_name" => "Komi"],
                        ["name" => "Kongo", "native_name" => "KiKongo"],
                        ["name" => "Korean", "native_name" => "한국어"],
                        ["name" => "Kurdish", "native_name" => "Kurdi"],
                        ["name" => "Kuanyama", "native_name" => "Kuanyama"],
                        ["name" => "Latin", "native_name" => "latine"],
                        ["name" => "Luxembourgish", "native_name" => " Letzebuergesch"],
                        ["name" => "Ganda", "native_name" => "Luganda"],
                        ["name" => "Limburgan", "native_name" => "Limburgs"],
                        ["name" => "Lingala", "native_name" => "Lingala"],
                        ["name" => "Lao", "native_name" => "Lao"],
                        ["name" => "Lithuanian", "native_name" => "lietuviu kalba"],
                        ["name" => "Luba-Katanga", "native_name" => "Kiluba"],
                        ["name" => "Latvian", "native_name" => "Iatviesu valoda"],
                        ["name" => "Manx", "native_name" => "Gaeig"],
                        ["name" => "Macedonian", "native_name" => "Macedonian"],
                        ["name" => "Malagasy", "native_name" => "Malagasy fiteny"],
                        ["name" => "Malay", "native_name" => "bahasa Melayu"],
                        ["name" => "Malayalam", "native_name" => "Malayalam"],
                        ["name" => "Maltese", "native_name" => " Malti"],
                        ["name" => "Maori", "native_name" => "te reo Maori"],
                        ["name" => "Marathi", "native_name" => "Marathi"],
                        ["name" => "Mongolian", "native_name" => "Mongolian"],
                        ["name" => "Nauru", "native_name" => "Ekakairu Naoero"],
                        ["name" => "Navajo", "native_name" => "Dine bizaad"],
                        ["name" => "Norwegian Bokmal", "native_name" => "Norsk bokmal"],
                        ["name" => "North Ndebele", "native_name" => "isiNdebele"],
                        ["name" => "Nepali", "native_name" => "Nepali"],
                        ["name" => "Ndonga", "native_name" => "Owambo"],
                        ["name" => "Norwegian Nynorsk", "native_name" => "Norsk nynorsk"],
                        ["name" => "Norwegian", "native_name" => "Norsk"],
                        ["name" => "South Ndebele ", "native_name" => "isiNdebele"],
                        ["name" => "Occitan", "native_name" => "Occitan"],
                        ["name" => "Ojibwa", "native_name" => "Afaan Oromoo"],
                        ["name" => "Oriya", "native_name" => "Oriya"],
                        ["name" => "Osssetic", "native_name" => "Osssetic"],
                        ["name" => "Punjabi", "native_name" => "Punjabi"],
                        ["name" => "Pali", "native_name" => "Pali"],
                        ["name" => "Persian", "native_name" => "Persian"],
                        ["name" => "Polish", "native_name" => "Perski"],
                        ["name" => "Pashto", "native_name" => "Pashto"],
                        ["name" => "Portuguese", "native_name" => "Português"],
                        ["name" => "Quechua", "native_name" => " Runa Simi"],
                        ["name" => "Romansh", "native_name" => "Romansh - rumantsch grischun"],
                        ["name" => "Rundi - KiRundi", "native_name"=> "Rundi - KiRundi"],
                        ["name" => "Romanian - Romana", "native_name"=> "Romanian - Romana"],
                        ["name" => "Russian", "native_name"=> "Русский"],
                        ["name" => "Sanskrit", "native_name"=> "Sanskrit"],
                        ["name" => "Sardinian - sardu", "native_name"=> "Sardinian - sardu"],
                        ["name" => "Northern Sami - Davvisamegiella", "native_name"=> "Northern Sami - Davvisamegiella"],
                        ["name" => "Samoan - gagana faa Samoa", "native_name"=> "Samoan - gagana faa Samoa"],
                        ["name" => "Sango", "native_name"=> "Sango"],
                        ["name" => "Serbian", "native_name"=> "Serbian"],
                        ["name" => "Scottish Gaelic", "native_name"=> "Scottish Gaelic"],
                        ["name" => "Shona - chiShona", "native_name"=> "Shona - chiShona"],
                        ["name" => "Sinhala", "native_name"=> "Sinhala"],
                        ["name" => "Slovak", "native_name"=> "Slovak"],
                        ["name" => "Somali - Soomaaliga", "native_name"=> "Somali - Soomaaliga"],
                        ["name" => "Spanish - espanol", "native_name"=> "Spanish - espanol"],
                        ["name" => "Southern Sotho - Sesotho", "native_name"=> "Southern Sotho - Sesotho"],
                        ["name" => "Sudanese - Basa Sunda", "native_name"=> "Sudanese - Basa Sunda"],
                        ["name" => "Swahili - Kiswahili", "native_name"=> "Swahili - Kiswahili"],
                        ["name" => "Swati - SiSwati", "native_name"=> "Swati - SiSwati"],
                        ["name" => "Tamil", "native_name"=> "Tamil"],
                        ["name" => "Telugu", "native_name"=> "Telugu"],
                        ["name" => "Tajik", "native_name"=> "Tajik"],
                        ["name" => "Thai", "native_name"=> "Thai"],
                        ["name" => "Tigrinya", "native_name"=> "Tigrinya"],
                        ["name" => "Tibetan", "native_name"=> "Tibetan"],
                        ["name" => "Turkmen", "native_name"=> "Turkmen"],
                        ["name" => "Tagalog - Wikang Tagalog", "native_name"=> "Tagalog - Wikang Tagalog"],
                        ["name" => "Tswana - Setswana", "native_name"=> "Tswana - Setswana"],
                        ["name" => "Togan - faka Tonga", "native_name"=> "Togan - faka Tonga"],
                        ["name" => "Turkish", "native_name"=> "Turkish"],
                        ["name" => "Tsonga - Xitsonga", "native_name"=> "Tsonga - Xitsonga"],
                        ["name" => "Tatar", "native_name"=> "Tatar"],
                        ["name" => "Twi", "native_name"=> "Twi"],
                        ["name" => "Tahitian - Reo Tahiti", "native_name"=> "Swedish - svenska"],
                        ["name" => "Uyghur", "native_name"=> "Swedish - svenska"],
                        ["name" => "Ukrainian", "native_name"=> "Ukrainian"],
                        ["name" => "Urdu", "native_name"=> "Urdu"],
                        ["name" => "Venda - Tshivenda", "native_name"=> "Venda - Tshivenda"],
                        ["name" => "Viet", "native_name"=> "Vietse"],
                        ["name" => "Volapuk", "native_name"=> "Volapuk"],
                        ["name" => "Walloon - Walon", "native_name"=> "Walloon - Walon"],
                        ["name" => "Welsh", "native_name"=> "Welsh"],
                        ["name" => "Wolof - Wollof", "native_name"=> "Wolof - Wollof"],
                        ["name" => "Western Frisian - Frysk", "native_name"=> "Western Frisian - Frysk"],
                        ["name" => "Xhosa - isiXhosa", "native_name"=> "Xhosa - isiXhosa"],
                        ["name" => "Yaddish", "native_name"=> "Yaddish"],
                        ["name" => "Yoruba", "native_name"=> "Yoruba"],
                        ["name" => "Zhuang", "native_name"=> "Zhuang"]
                    ];

                    foreach($languages as $language) {
                        Language::create($language);
                    }
                }
            }
            
            